# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random variable sampler using Rcpp
#' @description A random variable sampler using Rcpp
#' @param N the number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC = C_gaus(100)
#' }
#' @export
C_gaus <- function(n) {
    .Call('_SC19024_C_gaus', PACKAGE = 'SC19024', n)
}

#' @title compute the mean of a vector
#' @description A random variable sampler using Rcpp
#' @param N the number of samples
#' @return a random sample of size \code{n}
#' \dontrun{
#' rnC = C_mean(c(1,2,3,4,5))
#' }
#' @export
C_mean <- function(X) {
    .Call('_SC19024_C_mean', PACKAGE = 'SC19024', X)
}

#' @title A random variable sampler using Rcpp
#' @description A random variable sampler using Rcpp
#' @param N the number of samples
#' @return a random sample of size \code{n}
#' @importFrom Rcpp evalCpp
#' @useDynLib SC19024
#' @examples
#' \dontrun{
#' rnC = C_unif(100)
#' }
#' @export
C_unif <- function(n, low, up) {
    .Call('_SC19024_C_unif', PACKAGE = 'SC19024', n, low, up)
}

rcpp_hello_world <- function() {
    .Call('_SC19024_rcpp_hello_world', PACKAGE = 'SC19024')
}

